# Generated by Django 3.2.5 on 2024-01-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu_ano_saeb', models.IntegerField()),
                ('co_uf', models.IntegerField()),
                ('sg_uf', models.CharField(max_length=50)),
                ('no_uf', models.CharField(max_length=50)),
                ('co_municipio', models.IntegerField()),
                ('no_municipio', models.CharField(max_length=50)),
                ('id_escola', models.IntegerField()),
                ('no_escola', models.CharField(max_length=50)),
                ('tp_tipo_rede', models.IntegerField()),
                ('tp_localizacao', models.IntegerField()),
                ('tp_capital', models.IntegerField()),
                ('qtd_alunos_inse', models.IntegerField()),
                ('media_inse', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inse_classificacao', models.CharField(max_length=50)),
                ('pc_nivel_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pc_nivel_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pc_nivel_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pc_nivel_4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pc_nivel_5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pc_nivel_6', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pc_nivel_7', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pc_nivel_8', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
