# Generated by Django 3.2.5 on 2024-01-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='no_escola',
            field=models.CharField(max_length=150),
        ),
    ]
