# Generated by Django 3.2.5 on 2024-01-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseapp', '0002_alter_school_no_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id_escola',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
