export const data = [
    {
        "id_escola": 11024372,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EMEIEF ANA NERY",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 9,
        "media_inse": "4.74",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "11.11",
        "pc_nivel_3": "0.00",
        "pc_nivel_4": "55.56",
        "pc_nivel_5": "22.22",
        "pc_nivel_6": "11.11",
        "pc_nivel_7": "0.00",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11024666,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EMEIEF BOA ESPERANCA",
        "tp_tipo_rede": 3,
        "tp_localizacao": 2,
        "tp_capital": 2,
        "qtd_alunos_inse": 27,
        "media_inse": "4.84",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "11.08",
        "pc_nivel_3": "11.15",
        "pc_nivel_4": "40.79",
        "pc_nivel_5": "22.23",
        "pc_nivel_6": "7.34",
        "pc_nivel_7": "7.41",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11024682,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EEEFM EURIDICE LOPES PEDROSO",
        "tp_tipo_rede": 2,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 98,
        "media_inse": "4.75",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "1.29",
        "pc_nivel_2": "15.01",
        "pc_nivel_3": "20.89",
        "pc_nivel_4": "27.67",
        "pc_nivel_5": "20.03",
        "pc_nivel_6": "8.53",
        "pc_nivel_7": "5.67",
        "pc_nivel_8": "0.91"
    },
    {
        "id_escola": 11024828,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EMEIEF IZIDORO STEDILE",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 28,
        "media_inse": "4.97",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "3.42",
        "pc_nivel_3": "14.33",
        "pc_nivel_4": "42.99",
        "pc_nivel_5": "21.18",
        "pc_nivel_6": "14.33",
        "pc_nivel_7": "0.00",
        "pc_nivel_8": "3.74"
    },
    {
        "id_escola": 11024968,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EEEMTI JUSCELINO KUBITSCHEK DE OLIVEIRA",
        "tp_tipo_rede": 2,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 134,
        "media_inse": "5.13",
        "inse_classificacao": "Nível V",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "6.89",
        "pc_nivel_3": "15.30",
        "pc_nivel_4": "26.20",
        "pc_nivel_5": "20.90",
        "pc_nivel_6": "16.66",
        "pc_nivel_7": "11.76",
        "pc_nivel_8": "2.29"
    },
    {
        "id_escola": 11025077,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EMEIEF MARIA DE SOUZA PEGO",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 12,
        "media_inse": "4.53",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "9.03",
        "pc_nivel_3": "42.36",
        "pc_nivel_4": "33.33",
        "pc_nivel_5": "15.28",
        "pc_nivel_6": "0.00",
        "pc_nivel_7": "0.00",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11025310,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EMEIEF PEDRO ALEIXO",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 34,
        "media_inse": "4.73",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "8.63",
        "pc_nivel_3": "12.39",
        "pc_nivel_4": "56.63",
        "pc_nivel_5": "12.39",
        "pc_nivel_6": "9.96",
        "pc_nivel_7": "0.00",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11025352,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EMEIEF POTY",
        "tp_tipo_rede": 3,
        "tp_localizacao": 2,
        "tp_capital": 2,
        "qtd_alunos_inse": 27,
        "media_inse": "4.41",
        "inse_classificacao": "Nível III",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "14.67",
        "pc_nivel_3": "48.26",
        "pc_nivel_4": "29.73",
        "pc_nivel_5": "7.34",
        "pc_nivel_6": "0.00",
        "pc_nivel_7": "0.00",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11025620,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EEEF TANCREDO DE ALMEIDA NEVES",
        "tp_tipo_rede": 2,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 19,
        "media_inse": "4.73",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "15.79",
        "pc_nivel_3": "31.58",
        "pc_nivel_4": "21.05",
        "pc_nivel_5": "21.05",
        "pc_nivel_6": "5.26",
        "pc_nivel_7": "5.26",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11025638,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "COLEGIO TIRADENTES DA POLICIA MILITAR - CTPM XI",
        "tp_tipo_rede": 2,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 198,
        "media_inse": "4.85",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "1.57",
        "pc_nivel_2": "9.49",
        "pc_nivel_3": "24.60",
        "pc_nivel_4": "20.98",
        "pc_nivel_5": "25.83",
        "pc_nivel_6": "11.20",
        "pc_nivel_7": "5.90",
        "pc_nivel_8": "0.42"
    },
    {
        "id_escola": 11047461,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EMEIEF 17 DE JUNHO",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 69,
        "media_inse": "4.56",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "18.05",
        "pc_nivel_3": "31.45",
        "pc_nivel_4": "25.16",
        "pc_nivel_5": "18.53",
        "pc_nivel_6": "4.99",
        "pc_nivel_7": "1.82",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11050594,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100015,
        "no_municipio": "Alta Floresta D'Oeste",
        "no_escola": "EMEF MARIOMA PEREIRA DA SILVA",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 103,
        "media_inse": "4.99",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "9.37",
        "pc_nivel_3": "15.59",
        "pc_nivel_4": "27.86",
        "pc_nivel_5": "23.00",
        "pc_nivel_6": "17.28",
        "pc_nivel_7": "6.04",
        "pc_nivel_8": "0.85"
    },
    {
        "id_escola": 11006773,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EEEFM CORA CORALINA",
        "tp_tipo_rede": 2,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 395,
        "media_inse": "5.01",
        "inse_classificacao": "Nível V",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "7.00",
        "pc_nivel_3": "18.22",
        "pc_nivel_4": "26.61",
        "pc_nivel_5": "22.76",
        "pc_nivel_6": "14.80",
        "pc_nivel_7": "10.06",
        "pc_nivel_8": "0.54"
    },
    {
        "id_escola": 11006846,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EEEF ALBINA MARCIO SORDI",
        "tp_tipo_rede": 2,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 195,
        "media_inse": "5.20",
        "inse_classificacao": "Nível V",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "3.48",
        "pc_nivel_3": "14.65",
        "pc_nivel_4": "26.03",
        "pc_nivel_5": "22.70",
        "pc_nivel_6": "16.26",
        "pc_nivel_7": "15.87",
        "pc_nivel_8": "1.00"
    },
    {
        "id_escola": 11006854,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEFM ALDEMIR LIMA CANTANHEDE",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 61,
        "media_inse": "4.65",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "16.95",
        "pc_nivel_3": "25.80",
        "pc_nivel_4": "25.29",
        "pc_nivel_5": "22.39",
        "pc_nivel_6": "7.40",
        "pc_nivel_7": "2.17",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11006889,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EEEFM ANISIO TEIXEIRA",
        "tp_tipo_rede": 2,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 274,
        "media_inse": "4.80",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.58",
        "pc_nivel_2": "12.51",
        "pc_nivel_3": "22.63",
        "pc_nivel_4": "29.71",
        "pc_nivel_5": "15.53",
        "pc_nivel_6": "13.28",
        "pc_nivel_7": "5.40",
        "pc_nivel_8": "0.36"
    },
    {
        "id_escola": 11006900,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEIEF ARCO-IRIS",
        "tp_tipo_rede": 3,
        "tp_localizacao": 2,
        "tp_capital": 2,
        "qtd_alunos_inse": 27,
        "media_inse": "4.69",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "7.34",
        "pc_nivel_3": "40.70",
        "pc_nivel_4": "22.18",
        "pc_nivel_5": "26.03",
        "pc_nivel_6": "0.00",
        "pc_nivel_7": "3.75",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11007079,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEF DR DIRCEU DE ALMEIDA",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 70,
        "media_inse": "4.91",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "11.48",
        "pc_nivel_3": "16.00",
        "pc_nivel_4": "28.50",
        "pc_nivel_5": "29.71",
        "pc_nivel_6": "9.94",
        "pc_nivel_7": "1.26",
        "pc_nivel_8": "3.11"
    },
    {
        "id_escola": 11007168,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "COLEGIO TIRADENTES DA POLICIA MILITAR - CTPM III",
        "tp_tipo_rede": 2,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 176,
        "media_inse": "4.88",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.54",
        "pc_nivel_2": "4.57",
        "pc_nivel_3": "24.61",
        "pc_nivel_4": "29.32",
        "pc_nivel_5": "23.29",
        "pc_nivel_6": "13.04",
        "pc_nivel_7": "4.07",
        "pc_nivel_8": "0.55"
    },
    {
        "id_escola": 11007222,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEIEF JORGE TEIXEIRA",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 46,
        "media_inse": "4.53",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "22.52",
        "pc_nivel_3": "22.17",
        "pc_nivel_4": "25.83",
        "pc_nivel_5": "19.11",
        "pc_nivel_6": "8.02",
        "pc_nivel_7": "2.36",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11007249,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEIEF HENRIQUE DIAS",
        "tp_tipo_rede": 3,
        "tp_localizacao": 2,
        "tp_capital": 2,
        "qtd_alunos_inse": 29,
        "media_inse": "4.87",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "3.49",
        "pc_nivel_3": "27.44",
        "pc_nivel_4": "27.60",
        "pc_nivel_5": "27.67",
        "pc_nivel_6": "10.31",
        "pc_nivel_7": "3.49",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11007257,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEF IRENO ANTONIO BERTICELLI",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 55,
        "media_inse": "4.67",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "23.48",
        "pc_nivel_3": "19.44",
        "pc_nivel_4": "18.69",
        "pc_nivel_5": "29.04",
        "pc_nivel_6": "4.80",
        "pc_nivel_7": "2.27",
        "pc_nivel_8": "2.27"
    },
    {
        "id_escola": 11007281,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EEEFM JARDIM DAS PEDRAS",
        "tp_tipo_rede": 2,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 98,
        "media_inse": "4.75",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "1.30",
        "pc_nivel_2": "13.99",
        "pc_nivel_3": "26.29",
        "pc_nivel_4": "24.36",
        "pc_nivel_5": "16.31",
        "pc_nivel_6": "13.78",
        "pc_nivel_7": "2.76",
        "pc_nivel_8": "1.22"
    },
    {
        "id_escola": 11007346,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEIEF JORGE LUIZ MOULAZ",
        "tp_tipo_rede": 3,
        "tp_localizacao": 2,
        "tp_capital": 2,
        "qtd_alunos_inse": 29,
        "media_inse": "4.65",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "21.06",
        "pc_nivel_3": "13.75",
        "pc_nivel_4": "30.82",
        "pc_nivel_5": "30.82",
        "pc_nivel_6": "0.00",
        "pc_nivel_7": "3.55",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11007443,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEIEF MAFALDA RODRIGUES",
        "tp_tipo_rede": 3,
        "tp_localizacao": 2,
        "tp_capital": 2,
        "qtd_alunos_inse": 35,
        "media_inse": "4.68",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "14.62",
        "pc_nivel_3": "27.67",
        "pc_nivel_4": "25.22",
        "pc_nivel_5": "23.56",
        "pc_nivel_6": "8.93",
        "pc_nivel_7": "0.00",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11007451,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEFM MAGDALENA TAGLIAFERRO",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 153,
        "media_inse": "4.78",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.58",
        "pc_nivel_2": "14.44",
        "pc_nivel_3": "19.42",
        "pc_nivel_4": "33.83",
        "pc_nivel_5": "17.98",
        "pc_nivel_6": "4.62",
        "pc_nivel_7": "6.94",
        "pc_nivel_8": "2.19"
    },
    {
        "id_escola": 11007508,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEFM MARIO QUINTANA",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 82,
        "media_inse": "5.08",
        "inse_classificacao": "Nível V",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "8.63",
        "pc_nivel_3": "21.33",
        "pc_nivel_4": "18.39",
        "pc_nivel_5": "21.20",
        "pc_nivel_6": "17.78",
        "pc_nivel_7": "11.21",
        "pc_nivel_8": "1.47"
    },
    {
        "id_escola": 11007524,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EEEFM MIGRANTES",
        "tp_tipo_rede": 2,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 142,
        "media_inse": "5.27",
        "inse_classificacao": "Nível V",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "3.16",
        "pc_nivel_3": "10.66",
        "pc_nivel_4": "20.34",
        "pc_nivel_5": "27.69",
        "pc_nivel_6": "21.67",
        "pc_nivel_7": "15.84",
        "pc_nivel_8": "0.64"
    },
    {
        "id_escola": 11007605,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEIEF PADRE ANGELO SPADARI",
        "tp_tipo_rede": 3,
        "tp_localizacao": 2,
        "tp_capital": 2,
        "qtd_alunos_inse": 53,
        "media_inse": "4.71",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "9.76",
        "pc_nivel_3": "22.86",
        "pc_nivel_4": "30.61",
        "pc_nivel_5": "31.39",
        "pc_nivel_6": "3.37",
        "pc_nivel_7": "2.01",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11007702,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEIEF PROF PEDRO LOUBACK",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 47,
        "media_inse": "4.64",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "0.00",
        "pc_nivel_2": "18.99",
        "pc_nivel_3": "29.49",
        "pc_nivel_4": "21.01",
        "pc_nivel_5": "15.35",
        "pc_nivel_6": "8.69",
        "pc_nivel_7": "6.46",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11007710,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEF PROF VENANCIO KOTTWITZ",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 67,
        "media_inse": "4.44",
        "inse_classificacao": "Nível III",
        "pc_nivel_1": "3.60",
        "pc_nivel_2": "16.51",
        "pc_nivel_3": "35.25",
        "pc_nivel_4": "23.27",
        "pc_nivel_5": "15.42",
        "pc_nivel_6": "4.63",
        "pc_nivel_7": "1.31",
        "pc_nivel_8": "0.00"
    },
    {
        "id_escola": 11007737,
        "nu_ano_saeb": 2021,
        "co_uf": 11,
        "sg_uf": "RO",
        "no_uf": "Rondônia",
        "co_municipio": 1100023,
        "no_municipio": "Ariquemes",
        "no_escola": "EMEIEF ROBERTO TURBAY",
        "tp_tipo_rede": 3,
        "tp_localizacao": 1,
        "tp_capital": 2,
        "qtd_alunos_inse": 58,
        "media_inse": "4.51",
        "inse_classificacao": "Nível IV",
        "pc_nivel_1": "1.63",
        "pc_nivel_2": "18.45",
        "pc_nivel_3": "28.64",
        "pc_nivel_4": "30.33",
        "pc_nivel_5": "10.45",
        "pc_nivel_6": "8.46",
        "pc_nivel_7": "2.04",
        "pc_nivel_8": "0.00"
    }
  ];
    